deploy/urls.py
from django.conf.urls import url
from django.contrib import admin
from web.views import accounts
from web.views import project
from web.views import depart
from web.views import host
from web.views import user
from web.views import deploy
from web.views import script
# from web.views import online
from web.views import database
from web.views import online_detail

from web import views
# from web import urls as online_urls  # 二级路由

urlpatterns = [
    url(r'^$', accounts.login),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', accounts.login, name='login'),

    # url(r'^accounts/login/$', accounts.login, name='login'),
    # 注销
    url(r'^logout/$', accounts.logout),
    url(r'^check/code/$', accounts.check_code, name='check_code'),  # 验证码路径

    # 部门url
    url(r'^depart/list/$', depart.depart_list, name='depart_list'),
    url(r'^depart/add/$', depart.depart_add, name='depart_add'),
    url(r'^depart/edit/(\d+)/$', depart.depart_edit, name='depart_edit'),
    url(r'^depart/del/(\d+)/$', depart.depart_del, name='depart_del'),
    # host主机
    url(r'^host/list/$', host.host_list, name='host_list'),
    url(r'^host/add/$', host.host_add, name='host_add'),
    url(r'^host/edit/(\d+)/$', host.host_edit, name='host_edit'),
    url(r'^host/del/(\d+)/$', host.host_del, name='host_del'),
    # 用户列表
    url(r'^user/list/$', user.user_list, name='user_list'),
    url(r'^user/add/$', user.user_add, name='user_add'),
    url(r'^user/edit/(\d+)/$', user.user_edit, name='user_edit'),
    url(r'^user/del/(\d+)/$', user.user_del, name='user_del'),
    # 项目
    url(r'^project/list/$', project.project_list, name='project_list'),
    url(r'^project/add/$', project.project_add, name='project_add'),
    url(r'^project/edit/(\d+)/$', project.project_edit, name='project_edit'),
    url(r'^project/del/(\d+)/$', project.project_del, name='project_del'),
    # 搜索
    url(r'^search', project.search, name='search'),
    # 发布任务
    url(r'^deploy/list/(?P<project_id>\d+)/$', deploy.deploy_list, name='deploy_list'),
    # 添加发布任务
    url(r'^deploy/add/(?P<project_id>\d+)/$', deploy.deploy_add, name='deploy_add'),
    # url(r'^deploy/add/(?P<project_id>\d+)/$',views.deploy.deploy_add.as_view(),deploy.deploy_add, name='deploy_add'),

    url(r'^deploy/edit/(?P<project_id>\d+)/(?P<nid>\d+)/$', deploy.deploy_edit, name='deploy_edit'),
    url(r'^deploy/del/(?P<project_id>\d+)/(?P<nid>\d+)/$', deploy.deploy_del, name='deploy_del'),
    # url(r'^deploy/rollback/(?P<project_id>\d+)/(?P<nid>\d+)/$', deploy.deploy_rollback, name='deploy_rollback'),
    # 拉代码
    url(r'^deploy/fetch/(?P<project_id>\d+)/(?P<deploy_id>\d+)/$', deploy.deploy_fetch, name='deploy_fetch'),
    # 上传代码
    url(r'^deploy/push/(?P<project_id>\d+)/(?P<deploy_id>\d+)/$', deploy.deploy_push, name='deploy_push'),


    # url(r'^deploy/rollback_list/(?P<project_id>\d+)/$', deploy.deploy_rollback_list, name='deploy_rollback_list'),
    # 回滚
    url(r'^deploy/rollback/(?P<project_id>\d+)/(?P<deploy_id>\d+)/$', deploy.deploy_rollback, name='deploy_rollback'),
    # url(r'^deploy/rollback/(?P<project_id>\d+)/$', deploy.deploy_rollback, name='deploy_rollback'),

    # script
    url(r'^script/list/$',script.script_list,name='script_list'),
    url(r'^script/add/$',script.script_add,name='script_add'),
    url(r'^script/edit/(\d+)/$',script.script_edit,name='script_edit'),
    url(r'^script/del/(\d+)/$',script.script_del,name='script_del'),

    # 上线单列表
    url(r'^online/list/$', online_detail.online_list, name='online_list'),
    # 查看上线单详情
    url(r'^online/details/(\d+)/$', online_detail.online_detail,name="online_detail"),
    # 开发编辑上线单
    url(r'^online/edit/(\d+)/$', online_detail.online_edit,name="online_edit"),
    # 项目负责人审核上线单
    url(r'^project/online/edit/(\d+)/$', online_detail.project_online_edit,name="project_online_edit"),
    # 测试审核上线单
    url(r'^test/online/edit/(\d+)/$', online_detail.test_online_edit,name="test_online_edit"),
    # 运维审核上线单
    url(r'^op/online/edit/(\d+)/$', online_detail.op_online_edit,name="op_online_edit"),
    # 产品审核上线单
    url(r'^pm/online/edit/(\d+)/$', online_detail.pm_online_edit,name="pm_online_edit"),
    # 删除上线单
    url(r'^online/del/(\d+)/$', online_detail.online_del,name="online_del"),
    # 添加上线单
    url(r'^online/add/$', online_detail.online_add,name="online_add"),
    #数据库列表
    url(r'^database/list/$', database.database_list, name='database_list'),
    # 添加数据库修改申请单
    url(r'^database/add/$', database.database_add,name="database_add"),

    # 查看数据库申请单详情
    url(r'^database/details/(\d+)/$', database.database_detail,name="database_detail"),
    # 开发编辑数据库申请单
    url(r'^database/edit/(\d+)/$', database.database_edit, name="database_edit"),
    # 项目负责人审核数据库申请单
    url(r'^project_database/edit/(\d+)/$', database.project_database_edit, name="project_database_edit"),
    # 运维审核数据库申请单
    url(r'^op_database/edit/(\d+)/$', database.op_database_edit, name="op_database_edit"),
    # 项目负责人编辑数据库申请单
    url(r'^pm_database/edit/(\d+)/$', database.pm_database_edit, name="pm_database_edit"),
    # 删除数据库申请单
    url(r'^database/del/(\d+)/$', database.database_del,name="database_del"),


]

web/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from rbac.models import UserInfo  # 从rbac里面导入用户表


class UserInfo(AbstractUser):
    """
    用户表
    """
    # username = models.CharField(verbose_name='用户名', max_length=32)
    # password = models.CharField(verbose_name='密码', max_length=64)

    server_name = models.CharField(verbose_name='SSH用户名', max_length=32, blank=True)
    server_private_key = models.TextField(verbose_name='SSH私钥', blank=True)

    git_name = models.CharField(verbose_name='git用户名', max_length=32, null=True, blank=True)
    git_pwd = models.CharField(verbose_name='git密码', max_length=32, null=True, blank=True)
    wechat_user = models.CharField(u'微信用户名', max_length=64, null=True)
    # email = models.EmailField(u'邮箱', max_length=64)
    # name = models.CharField(u'姓名', max_length=64)
    jobs = models.CharField(u'工作职位', max_length=64, null=True)

    def __str__(self):
        return self.username

    class Meta:  # 表名显示中文

        verbose_name = "员工表"
        verbose_name_plural = verbose_name  # 复数的意思，如果不加这个后面会多个s


class Host(models.Model):
    """
    主机表
    """
    hostname = models.CharField(verbose_name='主机名', max_length=32)
    ssh_port = models.IntegerField(verbose_name='SSH端口')
    other = models.CharField(verbose_name='备注', max_length=32, blank=True)

    # Deploy = models.ForeignKey(verbose_name='发布任务', to='Deploy',null=True)

    def __str__(self):
        return self.hostname


class Department(models.Model):
    """
    部门表
    """
    title = models.CharField(verbose_name='部门', max_length=32)

    def __str__(self):
        return self.title


class Project(models.Model):
    """
    项目表
    """
    depart = models.ForeignKey(verbose_name='部门', on_delete=models.CASCADE, to='Department')
    title = models.CharField(verbose_name='项目名称', max_length=32)
    git = models.CharField(verbose_name='仓库地址', max_length=128)
    private = models.BooleanField(verbose_name='是否私有', default=True)
    online_path = models.CharField(verbose_name='线上项目路径', max_length=128)
    hosts = models.ManyToManyField(verbose_name='关联主机', to='Host')

    def __str__(self):
        return self.title


class Deploy(models.Model):
    """
    部署任务表
        例如：
            1       0.11
            2       1.10
            1       0.12
    """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    # version = models.CharField(verbose_name='版本', max_length=32)
    file = models.CharField(verbose_name='单文件列表', max_length=128, null=True)
    branch = models.CharField(verbose_name='分支', max_length=32, null=True)
    uid = models.CharField(verbose_name='上线文件包名称', max_length=32, null=True, blank=True)
    time = models.DateTimeField(verbose_name='拉取时间', auto_now_add=True, null=True)
    status_choice = (
        (1, '未获取'),
        (2, '待发布'),
        (3, '已发布'),

    )
    status = models.IntegerField(verbose_name='状态', choices=status_choice, default=1)
    script = models.ForeignKey(verbose_name='script', to='Script', null=True, blank=True, on_delete=models.CASCADE)


class DeployRecord(models.Model):
    """
    服务器部署记录
    """
    deploy = models.ForeignKey(verbose_name='部署任务', to='Deploy', on_delete=models.CASCADE, null=True)
    host = models.ForeignKey(verbose_name='主机', to='Host', on_delete=models.CASCADE, null=True)
    host_version = models.CharField(verbose_name='版本', max_length=32, null=True)

    status_choice = (
        (1, '发布中'),
        (2, '发布成功'),
        (3, '发布失败'),
    )
    status = models.IntegerField(verbose_name='状态', choices=status_choice, default=1, null=True)
    deploy_time = models.DateTimeField(verbose_name='发布时间', auto_now_add=True, null=True)

    log = models.TextField(verbose_name='日志')


class RollbackRecord(models.Model):
    """
    服务器回滚记录
    """
    deploy = models.ForeignKey(verbose_name='部署任务', to='Deploy', on_delete=models.CASCADE)
    host = models.ForeignKey(verbose_name='主机', to='Host', on_delete=models.CASCADE)
    host_version = models.CharField(verbose_name='版本', max_length=32, null=True)

    status_choice = (
        (1, '回滚中'),
        (2, '回滚成功'),
        (3, '回滚失败'),
    )
    status = models.IntegerField(verbose_name='状态', choices=status_choice, default=1)
    deploy_time = models.DateTimeField(verbose_name='回滚时间', auto_now_add=True)

    rollback_log = models.TextField(verbose_name='日志')


class Script(models.Model):
    """
    script
    """
    title = models.CharField(verbose_name='标题', max_length=128)
    interpreter_choices = {
        ('py', 'python3'),
        ('sh', 'bash')
    }
    interpreter = models.CharField(verbose_name='解释器', choices=interpreter_choices, default='py', max_length=16)
    code = models.TextField(verbose_name='上传脚本')
    rollback_code = models.TextField(verbose_name='回滚脚本', null=True)

    def __str__(self):
        return self.title


class Sqlcredential(models.Model):
    """
    数据库修改
    """
    database_name = models.CharField(verbose_name="修改库名", max_length=256)
    Apply_time = models.DateTimeField(verbose_name="申请日期")
    sql_yj = models.TextField(verbose_name='SQL语句', max_length=1024)
    select_project = models.CharField(verbose_name='选择项目负责人审核', max_length=128, null=True)
    select_test = models.CharField(verbose_name='指定测试审核', max_length=128, default="")
    select_op = models.CharField(verbose_name='指定运维审核', max_length=128, default="")
    Rollback_name = models.CharField(verbose_name='回滚方案', max_length=128, default="")
    Development_qz = models.CharField(verbose_name='开发签字', max_length=128, default="")
    Project_qz = models.CharField(verbose_name='项目负责人签字', max_length=128, default="")
    Technical_qz = models.CharField(verbose_name='技术总监签字', max_length=128, default="")
    op_qz = models.CharField(verbose_name='运维签字', max_length=256, default="")
    Project_confirm_qz = models.CharField(verbose_name='项目负责人（产品）确认签字', max_length=128, default="")
    # pm_qz = models.CharField(verbose_name='项目负责人（产品）确认签字', max_length=128,default="")
    status_choices = ((1, '提交更新'),
                      (2, '负责人审核通过'),
                      (3, '运维上线完成'),
                      (4, '否决上线'),
                      (5, '回滚'),
                      (6, '流程结束'))
    status = models.IntegerField(verbose_name='状态', choices=status_choices, default=1)
    staff = models.ForeignKey(to="UserInfo", on_delete=models.CASCADE, null=True)


class Onlinedetails(models.Model):
    """
    上线单详情
    """
    Online_project = models.CharField(verbose_name="上线项目(版本号)", max_length=256, blank=True)
    Online_time = models.DateTimeField(verbose_name="上线日期", max_length=256, null=True)
    Rollback_name = models.CharField(verbose_name='回滚方案', max_length=128, null=True)
    Online_step = models.TextField(verbose_name="上线步骤", null=True)
    Branch_status = models.CharField(verbose_name='分支合并状态', max_length=256)
    Influence = models.CharField(verbose_name='代码修改影响点', max_length=256)

    select_project = models.CharField(verbose_name='选择项目负责人审核', max_length=128, null=True, default="")
    select_test = models.CharField(verbose_name='指定测试审核', max_length=128, null=True, default="")
    select_op = models.CharField(verbose_name='指定运维审核', max_length=128, null=True, default="")

    Op_qz = models.CharField(verbose_name='运维签字', max_length=256, null=True, default="")
    Rd_qz = models.CharField(verbose_name='rd签字', max_length=256, null=True)
    Test_qz = models.CharField(verbose_name='测试签字', max_length=256, null=True, default="")
    Ui_qz = models.CharField(verbose_name='ui签字', max_length=256, null=True, default="")
    Pm_qz = models.CharField(verbose_name='产品签字', max_length=256, null=True, default="")
    Zj_qz = models.CharField(verbose_name='总监签字', max_length=256, null=True, default="")
    Rallback_result = models.CharField(verbose_name='回归结果测试产品签字', max_length=256, null=True, default="")
    status_choices = ((1, '提交更新'),
                      (2, '负责人审核通过'),
                      (3, '预上线'),
                      (4, '代码上线完成'),
                      (5, '回归中'),
                      (6, '回归完成'),
                      (7, '回滚'),
                      (8, '否决上线'),
                      (9, '流程结束'))
    status = models.IntegerField(verbose_name='状态', choices=status_choices, default=1)

    # details_id = models.OneToOneField(to="Onlinelist", on_delete=models.CASCADE) # 详情页
    # details = models.ForeignKey(to="Onlinelist", on_delete=models.CASCADE) # 详情页

    staff = models.ForeignKey(to="UserInfo", on_delete=models.CASCADE)  # 项目负责人

    class Meta:
        verbose_name = "上线单详情表"
        verbose_name_plural = verbose_name
# class Onlinelist(models.Model):
#     """
#     上线单列表
#     """
#     Online_project = models.CharField(verbose_name="上线项目(版本号)", max_length=256, blank=True)
#     Online_time = models.DateTimeField(verbose_name="上线日期", max_length=256, blank=True)
#     Rollback_name = models.CharField(verbose_name='回滚方案', max_length=128,)
#     select_project= models.CharField(verbose_name='选择项目负责人审核', max_length=128,)
#     select_test= models.CharField(verbose_name='指定测试审核', max_length=128,)
#     select_op= models.CharField(verbose_name='指定运维审核', max_length=128)
#     Op_qz = models.CharField(verbose_name='运维签字', max_length=256)
#     Rd_qz = models.CharField(verbose_name='rd签字', max_length=256)
#     Test_qz = models.CharField(verbose_name='测试签字', max_length=256)
#     Ui_qz = models.CharField(verbose_name='ui签字', max_length=256)
#     Pm_qz = models.CharField(verbose_name='产品签字', max_length=256)
#     Zj_qz = models.CharField(verbose_name='总监签字', max_length=256)
#     Rallback_result = models.CharField(verbose_name='回归结果测试产品签字', max_length=256)
#     status_choices = ((1, '提交更新'),
#                       (2, '负责人审核通过'),
#                       (3, '预上线'),
#                       (4, '代码上线完成'),
#                       (5, '回归中'),
#                       (6, '回归完成'),
#                       (7, '回滚'),
#                       (8, '否决上线'),

web/templates/branch.html
{% extends 'layout.html' %}
{% load web %}

{% block content %}

{% endblock %}

{% block js %}
    <script>
     alert('此分支没有合并')

    </script>
{% endblock %}

web/templates/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        <form method="post">
            {% csrf_token %}
            <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


            <div style="margin-top: 20px;">
                <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                <input type="submit" class="btn btn-danger btn-sm" value="确 认">
            </div>
        </form>
    </div>

{% endblock %}

web/templates/depart_list.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <h1>部门列表</h1>
    <div>
        <a class="btn btn-primary" href="{% memory_url request 'depart_add' %}">添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in depart_queryset %}
            <tr>
                <td>{{ row.title }}</td>
                <td>
                    <a href="{% memory_url request 'depart_edit' row.id %}">编辑</a>
                    <a href="{% memory_url request 'depart_del' row.id %}">删除</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pager.page_html|safe }}
        </ul>
    </nav>
{% endblock %}

web/templates/edit_online.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <h1>编辑上线单</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">上线项目(版本号)</label>
                        <input type="text" id="title" name="Online_project" class="form-control"
                               value="{{ report.Online_project }}">
                    </div>

                    <div class="form-group">
                        <label for="title">上线日期</label>
                        <input type="text" id="test1" name="Online_time" class="form-control"
                               value="{{ report.Online_time|date:"Y-m-d" }}">
                    </div>
                    <div class="form-group">
                        <label for="content">上线步骤（RD提供）</label>
                        <textarea class="form-control" name="Online_step" id="content"
                                  rows="20">{{ report.onlinedetails.Online_step }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="title">回滚方案</label>
                        <input type="text" id="title" name="Rollback_name" class="form-control"
                               value="{{ report.Rollback_name }}">
                    </div>

                    <div class="form-group">
                        <label for="title">分支合并状态</label>
                        <input type="text" id="title" name="Branch_status" class="form-control"
                               value="{{ report.onlinedetails.Branch_status }}">
                    </div>
                    <div class="form-group">
                        <label for="title">代码修改后影响点</label>
                        <input type="text" id="title" name="Influence" class="form-control"
                               value="{{ report.onlinedetails.Influence }}">
                    </div>
                    <div class="form-group">
                        <label for="title">rd确认签字</label>
                        <input type="text" id="title" name="Rd_qz" class="form-control" value="{{ report.Rd_qz }}">
                    </div>
                    <div class="form-group">
                        <label for="title">部分总监/负责人签字</label>
                        <input type="text" id="title" name="Zj_qz" class="form-control" value="{{ report.Zj_qz }}">
                    </div>
                    <div class="form-group">
                        <label for="title">项目重要功能(测试签字)</label>
                        <input type="text" id="title" name="Test_qz" class="form-control" value="{{ report.Test_qz }}">
                    </div>
                    <div class="form-group">
                        <label for="title">运维签字</label>
                        <input type="text" id="title" name="Op_qz" class="form-control" value="{{ report.Op_qz }}">
                    </div>
                    <div class="form-group">
                        <label for="title">UI签字</label>
                        <input type="text" id="title" name="Ui_qz" class="form-control" value="{{ report.Ui_qz }}">
                    </div>
                    <div class="form-group">
                        <label for="title">PM,UE签字</label>
                        <input type="text" id="title" name="Pm_qz" class="form-control" value="{{ report.Pm_qz }}">
                    </div>

                    <div class="form-group">
                        <label for="title">上线回归结果（测试及产品签字）</label>
                        <input type="text" id="title" name="Rallback_result" class="form-control"
                               value="{{ report.Rallback_result }}">
                    </div>

                    <button class="btn btn-success" type="submit">发布</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

{% block js %}
    <script src="/static/laydate/laydate.js"></script>
    <script>
        //执行一个laydate实例
        laydate.render({
            elem: '#test1',

        });
    </script>

{% endblock %}

web/templates/form.html
{% extends 'layout.html' %}


{% block content %}

    <form method="post" class="form-horizontal" novalidate>
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label class="col-sm-2 control-label" >{{ field.label }}：</label>
                <div class="col-sm-9">
                    {{ field }} <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
                <input type="submit" class="btn btn-primary" value="提交">
            </div>
        </div>
    </form>
{% endblock %}

{% block js %}
    <script src="/static/laydate/laydate.js"></script>
    <script>
        //执行一个laydate实例
        laydate.render({
            elem: '#id_Apply_time',

        });
    </script>

{% endblock %}

web/templates/host_list.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <h1>主机列表</h1>
    <div>
        <a class="btn btn-primary" href="{% memory_url request 'host_add' %}">添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>主机名</th>
            <th>端口</th>
            <th>操作</th>
            <th>备注</th>
        </tr>
        </thead>
        <tbody>
        {% for row in depart_queryset %}
            <tr>
                <td>{{ row.hostname }}</td>
                <td>{{ row.ssh_port }}</td>
                <td>{{ row.other}}</td>
                <td>
                    <a href="{% memory_url request 'host_edit' row.id %}">编辑</a>
                    <a href="{% memory_url request 'host_del' row.id %}">删除</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pager.page_html|safe }}
        </ul>
    </nav>
{% endblock %}

web/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bg.css' %}">
</head>
<body>
<div style="width: 400px; height:600px; margin: 0 auto;margin-top: 280px;" >
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="user" class="col-sm-3 control-label">用户名</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="user" name="username">
            </div>
        </div>
        <div class="form-group">
            <label for="pwd" class="col-sm-3 control-label">密码</label>
            <div class="col-sm-9">
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
        </div>
         <div class="form-group">
            <label for="code" class="col-sm-3 control-label">验证码</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="code" name="code">
            </div>
             <div class="col-sm-4">
                 <img onclick="changeImage(this);" src="/check/code/"  title="点击刷新">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-primary">登 录</button>
                <span style="color: red">{{ error }}</span>
            </div>
        </div>
    </form>
</div>
<script>
    function changeImage(ths) {
        ths.src = ths.src + '?'

    }
</script>
</body>
</html>

web/templates/project_list.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <div class="luffy-container">
        <div>
            <a class="btn btn-primary" href="{% memory_url request 'project_add' %}">添加</a>


        </div>
        <div class="right" style="margin-left: 911px">
            <form method="get" action="{% url 'search' %}">
                {#                  {% csrf_token %}#}
                <input name="q" type="search" placeholder="请输入项目名字" required>
                <button type="submit">搜索</button>
            </form>

        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>项目名称</th>
                <th>仓库地址</th>
                <th>上线</th>
{#                <th>回滚</th>#}
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in depart_queryset %}
                <tr>
                    <td>{{ row.title }}</td>
                    <td>{{ row.git }}</td>
                    <td>
                        <a class="btn btn-success" target="_blank"
                           href="{% url 'deploy_list' project_id=row.id %}">上线</a>

                    </td>
{#                    <td>#}
{#                        <a class="btn btn-info" target="_blank"#}
{#                           href="{% url 'deploy_rollback' project_id=row.id %}">回滚</a>#}
{#                    </td>#}
                    <td>
                        <a class="btn btn-info" href="{% memory_url request 'project_edit' row.id %}">编辑</a>
                        <a class="btn btn-danger" href="{% memory_url request 'project_del' row.id %}">删除</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ pager.page_html|safe }}
            </ul>
        </nav>

    </div>
{% endblock %}

web/templates/script_list.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <h1>脚本列表</h1>
    <div>
        <a class="btn btn-primary" href="{% memory_url request 'script_add' %}">添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>解释器</th>
{#            <th>脚本内容</th>#}
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in depart_queryset %}
            <tr>
                <td>{{ row.title }}</td>
                <td>{{ row.interpreter }}</td>
{#                <td>{{ row.code }}</td>#}
                <td>
                    <a href="{% memory_url request 'script_edit' row.id %}">编辑</a>
                    <a href="{% memory_url request 'script_del' row.id %}">删除</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pager.page_html|safe }}
        </ul>
    </nav>
{% endblock %}

web/templates/user_list.html
{% extends 'layout.html' %}
{% load web %}
{% block content %}
    <h1>用户列表</h1>
    <div>
        <a class="btn btn-primary" href="{% memory_url request 'user_add' %}">添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>用户名</th>
            <th>SSH账号</th>
            <th>角色</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in depart_queryset %}
            <tr>
                <td>{{ row.username }}</td>
                <td>{{ row.server_name }}</td>
                <td>{{ row.jobs }}</td>
                <td>
                    <a href="{% memory_url request 'user_edit' row.id %}">编辑</a>
                    <a href="{% memory_url request 'user_del' row.id %}">删除</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pager.page_html|safe }}
        </ul>
    </nav>
{% endblock %}